# Generated by Django 2.2.6 on 2019-10-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelmy', '0003_auto_20191027_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='sub_text',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
