# Generated by Django 2.2.6 on 2019-10-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelmy', '0004_destination_sub_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='todo_desc3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
