# Generated by Django 2.2.6 on 2019-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelmy', '0005_destination_todo_desc3'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='todo_desc4',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='todo_img4',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='todo_title4',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
