# Generated by Django 2.2.6 on 2019-10-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelmy', '0006_auto_20191027_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='hotel_url1',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
